
# class RenderConfig:
    
SPHERE_RADIUS = 10
SPHERE_RESULUTION = 100
    
#Cam default position
INITIAL_ZOOM = -20
INITIAL_ROT_X = -100
INITIAL_ROT_Y = 40
# INITIAL_ROT_Z = 0
INITIAL_TILT_X = 0
INITIAL_TILT_Y = 0
# INITIAL_TILT_Y = 0
    
DEFAULT_FOV = 45
NEAR_CLIP = 0.1
FAR_CLIP = 100.0
    
ROTATE_SENSITIVITY = 0.5
TILTING_SENSITIVITY = 0.05
ZOOM_SENSITIVITY = 1.5
MAX_ZOOM_IN = -(SPHERE_RADIUS + 0.5)

MIN_WINDOW_WIDTH = 800
MIN_WINDOW_HEIGHT = 600